#!/usr/bin/env bash

role=${CONTAINER_ROLE:-app}

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ "$role" = "app" ]; then
    if [ $# -gt 0 ]; then
        exec gosu $WWWUSER "$@"
    else
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    fi
elif [ "$role" = "queue" ]; then
    echo "Running the queue..."
    php /var/www/html/artisan queue:work
elif [ "$role" = "scheduler" ]; then
    while true
    do
      php /var/www/html/artisan schedule:run --verbose --no-interaction &
      sleep 60
    done
else
    echo "Could not match the container role \"$role\""
    exit 1
fi
